import { applyBestPractices } from './bestPracticesRules.js';

/**
 * Generates the full cdm.properties file content as a string.
 *
 * @param {object} formState - Complete form state from App.jsx
 * @returns {string} The generated .properties file content
 */
export function generateProperties(formState) {
  const {
    // Connection
    originHost,
    originPort,
    originUsername,
    originPassword,
    originConnectionType,
    originScb,
    originScbMethod,
    originAstraDatabaseId,
    originScbType,
    originScbRegion,
    originScbCustomDomain,
    targetHost,
    targetPort,
    targetUsername,
    targetPassword,
    targetConnectionType,
    targetScb,
    targetScbMethod,
    targetAstraDatabaseId,
    targetScbType,
    targetScbRegion,
    targetScbCustomDomain,

    // Schema
    originSchema, // parsed schema object
    targetSchema, // parsed schema object

    // Performance hints
    rowCount,
    tableSizeGB,
    dataTypes,

    // Advanced features
    explodeMapEnabled,
    explodeMapOriginColumn,
    explodeMapTargetKeyColumn,
    explodeMapTargetValueColumn,
    constantColumnsEnabled,
    constantColumnsNames,
    constantColumnsTypes,
    constantColumnsValues,
    extractJsonEnabled,
    extractJsonOriginColumn,
    extractJsonPropertyMapping,
    extractJsonExclusive,

    // Autocorrect
    autocorrectMissing,
    autocorrectMismatch,

    // TrackRun
    trackRun,
    trackRunAutoRerun,
  } = formState;

  const { props: bpProps, comments: bpComments } = applyBestPractices({
    originSchema,
    targetSchema,
    rowCount: rowCount || null,
    tableSizeGB: tableSizeGB || null,
    dataTypes: dataTypes || [],
  });

  const lines = [];

  const pad = (key) => key.padEnd(52);
  const prop = (key, value, comment) => {
    if (comment) lines.push(`# ${comment}`);
    lines.push(`${pad(key)}${value}`);
  };
  const commentedProp = (key, value, comment) => {
    if (comment) lines.push(`# ${comment}`);
    lines.push(`#${pad(key)}${value}`);
  };
  const section = (title, description) => {
    lines.push('');
    lines.push('#' + '='.repeat(99));
    lines.push(`# ${title}`);
    if (description) {
      description.split('\n').forEach((l) => lines.push(`# ${l}`));
    }
    lines.push('#' + '-'.repeat(99));
  };

  // ── Header ────────────────────────────────────────────────────────────────
  lines.push('# Generated by CDM Config Builder');
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  lines.push('#');
  lines.push('# Reference: https://github.com/datastax/cassandra-data-migrator');
  lines.push('# Full property reference: cdm-detailed.properties');
  lines.push('');

  // ── Connection ────────────────────────────────────────────────────────────
  section('ORIGIN CONNECTION', 'Connection settings for the source Cassandra cluster.');

  if (originConnectionType === 'scb') {
    const method = originScbMethod || 'provide';
    if (method === 'provide') {
      prop(
        'spark.cdm.connect.origin.scb',
        originScb || 'file:///path/to/secure-connect-origin.zip',
        'Astra Secure Connect Bundle path.'
      );
    } else {
      // auto-download
      prop(
        'spark.cdm.connect.origin.astra.database.id',
        originAstraDatabaseId || 'your-astra-database-id',
        'Astra Database UUID for auto-downloading the Secure Connect Bundle.'
      );
      const scbType = originScbType || 'default';
      prop('spark.cdm.connect.origin.astra.scb.type', scbType, "SCB type: 'default' or 'custom'.");
      if (scbType === 'custom') {
        prop(
          'spark.cdm.connect.origin.astra.scb.region',
          originScbRegion || 'us-east-1',
          'Region name for the regional secure bundle (required when scb.type is custom).'
        );
        prop(
          'spark.cdm.connect.origin.astra.scb.custom.domain',
          originScbCustomDomain || 'your-custom-domain.example.com',
          'Custom domain for secure connect bundles (required when scb.type is custom).'
        );
      }
    }
  } else {
    prop(
      'spark.cdm.connect.origin.host',
      originHost || 'localhost',
      'Hostname or IP of the origin Cassandra cluster. Can be comma-separated for multiple contact points.'
    );
    prop(
      'spark.cdm.connect.origin.port',
      originPort || 9042,
      'CQL native transport port (default: 9042).'
    );
  }
  prop(
    'spark.cdm.connect.origin.username',
    originConnectionType === 'scb' ? 'token' : originUsername || 'cassandra',
    originConnectionType === 'scb'
      ? 'Astra token identifier (fixed value: token).'
      : 'Username for origin authentication.'
  );
  prop(
    'spark.cdm.connect.origin.password',
    originConnectionType === 'scb'
      ? originPassword || 'AstraCS:your-token-here'
      : originPassword || 'cassandra',
    originConnectionType === 'scb'
      ? 'Astra application token (starts with AstraCS:...).'
      : 'Password for origin authentication.'
  );

  section('TARGET CONNECTION', 'Connection settings for the destination Cassandra cluster.');

  if (targetConnectionType === 'scb') {
    const method = targetScbMethod || 'provide';
    if (method === 'provide') {
      prop(
        'spark.cdm.connect.target.scb',
        targetScb || 'file:///path/to/secure-connect-target.zip',
        'Astra Secure Connect Bundle path.'
      );
    } else {
      // auto-download
      prop(
        'spark.cdm.connect.target.astra.database.id',
        targetAstraDatabaseId || 'your-astra-database-id',
        'Astra Database UUID for auto-downloading the Secure Connect Bundle.'
      );
      const scbType = targetScbType || 'default';
      prop('spark.cdm.connect.target.astra.scb.type', scbType, "SCB type: 'default' or 'custom'.");
      if (scbType === 'custom') {
        prop(
          'spark.cdm.connect.target.astra.scb.region',
          targetScbRegion || 'us-east-1',
          'Region name for the regional secure bundle (required when scb.type is custom).'
        );
        prop(
          'spark.cdm.connect.target.astra.scb.custom.domain',
          targetScbCustomDomain || 'your-custom-domain.example.com',
          'Custom domain for secure connect bundles (required when scb.type is custom).'
        );
      }
    }
  } else {
    prop(
      'spark.cdm.connect.target.host',
      targetHost || 'localhost',
      'Hostname or IP of the target Cassandra cluster.'
    );
    prop(
      'spark.cdm.connect.target.port',
      targetPort || 9042,
      'CQL native transport port (default: 9042).'
    );
  }
  prop(
    'spark.cdm.connect.target.username',
    targetConnectionType === 'scb' ? 'token' : targetUsername || 'cassandra',
    targetConnectionType === 'scb'
      ? 'Astra token identifier (fixed value: token).'
      : 'Username for target authentication.'
  );
  prop(
    'spark.cdm.connect.target.password',
    targetConnectionType === 'scb'
      ? targetPassword || 'AstraCS:your-token-here'
      : targetPassword || 'cassandra',
    targetConnectionType === 'scb'
      ? 'Astra application token (starts with AstraCS:...).'
      : 'Password for target authentication.'
  );

  // ── Schema ────────────────────────────────────────────────────────────────
  section('SCHEMA', 'Origin and target table schema configuration.');

  const originKsTable = originSchema?.keyspaceTable || 'keyspace_name.table_name';
  prop(
    'spark.cdm.schema.origin.keyspaceTable',
    originKsTable,
    'Required: <keyspace>.<table> of the origin table to migrate.'
  );

  const targetKsTable = targetSchema?.keyspaceTable;
  if (targetKsTable && targetKsTable !== originKsTable) {
    prop(
      'spark.cdm.schema.target.keyspaceTable',
      targetKsTable,
      'Target table differs from origin. Specify when keyspace or table name changes.'
    );
  } else {
    commentedProp(
      'spark.cdm.schema.target.keyspaceTable',
      targetKsTable || originKsTable,
      'Uncomment if target keyspace/table name differs from origin.'
    );
  }

  lines.push('');
  prop(
    'spark.cdm.schema.origin.column.ttl.automatic',
    'true',
    'Automatically determine TTL from the max TTL of all eligible non-PK columns.'
  );
  prop(
    'spark.cdm.schema.origin.column.writetime.automatic',
    'true',
    'Automatically determine WRITETIME from the max WRITETIME of all eligible non-PK columns.'
  );

  if (bpProps['spark.cdm.schema.ttlwritetime.calc.useCollections'] !== undefined) {
    prop(
      'spark.cdm.schema.ttlwritetime.calc.useCollections',
      String(bpProps['spark.cdm.schema.ttlwritetime.calc.useCollections']),
      bpComments['spark.cdm.schema.ttlwritetime.calc.useCollections']
    );
  } else {
    commentedProp(
      'spark.cdm.schema.ttlwritetime.calc.useCollections',
      'false',
      'Set to true if non-key columns are only collections/UDTs (needed for correct TTL/WRITETIME).'
    );
  }

  // ── Autocorrect ───────────────────────────────────────────────────────────
  section(
    'AUTOCORRECT (DiffData job only)',
    'Controls whether the validation job auto-fixes differences.\nLeave false for read-only validation; enable only after reviewing discrepancies.'
  );

  prop(
    'spark.cdm.autocorrect.missing',
    autocorrectMissing ? 'true' : 'false',
    'When true, rows missing in target (but present in origin) will be re-migrated during validation.'
  );
  prop(
    'spark.cdm.autocorrect.mismatch',
    autocorrectMismatch ? 'true' : 'false',
    'When true, rows with field differences between origin and target will be updated in target.'
  );

  if (bpProps['spark.cdm.autocorrect.missing.counter'] !== undefined) {
    prop(
      'spark.cdm.autocorrect.missing.counter',
      'false',
      bpComments['spark.cdm.autocorrect.missing.counter']
    );
  }

  // ── Track Run ─────────────────────────────────────────────────────────────
  section(
    'TRACK RUN',
    'Enables run tracking so migrations can be resumed after interruption.\nRun details are stored in cdm_run_info and cdm_run_details tables on the target keyspace.'
  );

  const trackRunComment =
    bpComments['spark.cdm.trackRun'] ||
    'When true, tracks each token-range status so the job can be resumed if interrupted.';
  prop('spark.cdm.trackRun', trackRun ? 'true' : 'false', trackRunComment);

  if (trackRun) {
    prop(
      'spark.cdm.trackRun.autoRerun',
      trackRunAutoRerun ? 'true' : 'false',
      'When true, automatically resumes from the last incomplete run.'
    );
    commentedProp(
      'spark.cdm.trackRun.previousRunId',
      '0',
      'Uncomment and set to a specific run ID to resume a particular previous run.'
    );
  } else {
    commentedProp(
      'spark.cdm.trackRun.autoRerun',
      'false',
      'Uncomment and set to true to auto-resume from last incomplete run.'
    );
  }

  // ── Performance ───────────────────────────────────────────────────────────
  section(
    'PERFORMANCE',
    'Tuning parameters for throughput and resource usage.\nSee cdm-detailed.properties for full documentation.'
  );

  if (bpComments['spark_cluster_recommendation']) {
    lines.push(`# ⚠ ${bpComments['spark_cluster_recommendation']}`);
    lines.push('');
  }

  prop(
    'spark.cdm.perfops.numParts',
    String(bpProps['spark.cdm.perfops.numParts']),
    bpComments['spark.cdm.perfops.numParts']
  );
  prop(
    'spark.cdm.perfops.batchSize',
    String(bpProps['spark.cdm.perfops.batchSize']),
    bpComments['spark.cdm.perfops.batchSize']
  );
  prop(
    'spark.cdm.perfops.ratelimit.origin',
    String(bpProps['spark.cdm.perfops.ratelimit.origin']),
    bpComments['spark.cdm.perfops.ratelimit.origin']
  );
  prop(
    'spark.cdm.perfops.ratelimit.target',
    String(bpProps['spark.cdm.perfops.ratelimit.target']),
    bpComments['spark.cdm.perfops.ratelimit.target']
  );

  if (bpProps['spark.cdm.perfops.fetchSizeInRows']) {
    prop(
      'spark.cdm.perfops.fetchSizeInRows',
      String(bpProps['spark.cdm.perfops.fetchSizeInRows']),
      bpComments['spark.cdm.perfops.fetchSizeInRows']
    );
  } else {
    commentedProp(
      'spark.cdm.perfops.fetchSizeInRows',
      '1000',
      'Default 1000. Reduce for tables with very large rows (>100KB) to avoid OOM.'
    );
  }

  commentedProp(
    'spark.cdm.perfops.consistency.read',
    'LOCAL_QUORUM',
    'Read consistency from origin. Options: ANY, ONE, TWO, THREE, QUORUM, LOCAL_ONE, LOCAL_QUORUM, ALL.'
  );
  commentedProp(
    'spark.cdm.perfops.consistency.write',
    'LOCAL_QUORUM',
    'Write consistency to target.'
  );

  // ── Transformation / Codecs ───────────────────────────────────────────────
  section('TRANSFORMATION & CODECS', 'Type conversion codecs and data transformation settings.');

  if (bpComments['spark.cdm.transform.codecs']) {
    lines.push(`# ${bpComments['spark.cdm.transform.codecs']}`);
  }
  if (bpComments['spark.cdm.transform.codecs_numerics']) {
    lines.push(`# ${bpComments['spark.cdm.transform.codecs_numerics']}`);
  }

  commentedProp(
    'spark.cdm.transform.codecs',
    '',
    'Comma-separated list: INT_STRING, DOUBLE_STRING, BIGINT_STRING, DECIMAL_STRING,\n' +
      '#   STRING_BLOB, ASCII_BLOB, TIMESTAMP_STRING_MILLIS, TIMESTAMP_STRING_FORMAT'
  );
  commentedProp(
    'spark.cdm.transform.codecs.timestamp.string.format',
    'yyyyMMddHHmmss',
    'Date format pattern for TIMESTAMP_STRING_FORMAT codec (uses DateTimeFormatter).'
  );
  commentedProp(
    'spark.cdm.transform.codecs.timestamp.string.zone',
    'UTC',
    'Timezone for TIMESTAMP_STRING_FORMAT codec.'
  );
  commentedProp(
    'spark.cdm.transform.custom.writetime',
    '0',
    'Fixed WRITETIME (microseconds since epoch) for all target rows. 0 = disabled.'
  );
  commentedProp(
    'spark.cdm.transform.custom.ttl',
    '0',
    'Fixed TTL (seconds) for all target rows. 0 = no expiry.'
  );
  commentedProp(
    'spark.cdm.transform.custom.writetime.incrementBy',
    '0',
    'Increment WRITETIME by this many microseconds on each re-run. ' +
      'Useful to prevent duplicate list entries when autocorrect runs multiple times.'
  );

  // ── Advanced Features ─────────────────────────────────────────────────────
  section(
    'ADVANCED FEATURES',
    'Optional schema transformation features: ExplodeMap, ConstantColumns, ExtractJson.'
  );

  // ExplodeMap
  if (explodeMapEnabled && explodeMapOriginColumn) {
    lines.push('# ExplodeMap: converts a MAP column in origin into multiple rows in target.');
    prop(
      'spark.cdm.feature.explodeMap.origin.name',
      explodeMapOriginColumn,
      'Name of the MAP column in the origin table to explode into multiple target rows.'
    );
    prop(
      'spark.cdm.feature.explodeMap.target.name.key',
      explodeMapTargetKeyColumn || 'map_key',
      'Target column that will hold the map key (must be part of target primary key).'
    );
    prop(
      'spark.cdm.feature.explodeMap.target.name.value',
      explodeMapTargetValueColumn || 'map_value',
      'Target column that will hold the map value.'
    );
  } else {
    lines.push('# ExplodeMap: converts a MAP column in origin into multiple rows in target.');
    commentedProp(
      'spark.cdm.feature.explodeMap.origin.name',
      'my_map_column',
      'Name of the MAP column in origin to explode.'
    );
    commentedProp(
      'spark.cdm.feature.explodeMap.target.name.key',
      'map_key',
      'Target PK column for map key.'
    );
    commentedProp(
      'spark.cdm.feature.explodeMap.target.name.value',
      'map_value',
      'Target column for map value.'
    );
  }

  lines.push('');

  // ConstantColumns
  if (constantColumnsEnabled && constantColumnsNames) {
    lines.push(
      '# ConstantColumns: inject fixed constant values into target columns not present in origin.'
    );
    prop(
      'spark.cdm.feature.constantColumns.names',
      constantColumnsNames,
      'Comma-separated list of target column names to inject as constants.'
    );
    prop(
      'spark.cdm.feature.constantColumns.types',
      constantColumnsTypes || '',
      'Comma-separated CQL types for each constant column (e.g., text, int, boolean).'
    );
    prop(
      'spark.cdm.feature.constantColumns.values',
      constantColumnsValues || '',
      "Comma-separated values (use CQL syntax: 'string', 1234, true)."
    );
  } else {
    lines.push(
      '# ConstantColumns: inject fixed constant values into target columns not present in origin.'
    );
    commentedProp(
      'spark.cdm.feature.constantColumns.names',
      'col1,col2',
      'Comma-separated target column names.'
    );
    commentedProp(
      'spark.cdm.feature.constantColumns.types',
      'text,int',
      'CQL types for each constant column.'
    );
    commentedProp(
      'spark.cdm.feature.constantColumns.values',
      "'value1',42",
      "Values in CQL syntax: 'string', number, true/false."
    );
  }

  lines.push('');

  // ExtractJson
  if (extractJsonEnabled && extractJsonOriginColumn) {
    lines.push(
      '# ExtractJson: extract a JSON property from an origin TEXT column into a target column.'
    );
    prop(
      'spark.cdm.feature.extractJson.originColumn',
      extractJsonOriginColumn,
      'Origin column (TEXT type) containing JSON content.'
    );
    prop(
      'spark.cdm.feature.extractJson.propertyMapping',
      extractJsonPropertyMapping || 'json_property:target_column',
      'Mapping: origin_json_property:target_column_name.'
    );
    if (extractJsonExclusive) {
      prop(
        'spark.cdm.feature.extractJson.exclusive',
        'true',
        'When true, only the mapped columns are processed; all others are ignored.'
      );
    } else {
      commentedProp(
        'spark.cdm.feature.extractJson.exclusive',
        'false',
        'Set to true to process only the mapped columns.'
      );
    }
  } else {
    lines.push(
      '# ExtractJson: extract a JSON property from an origin TEXT column into a target column.'
    );
    commentedProp(
      'spark.cdm.feature.extractJson.originColumn',
      'json_column',
      'Origin TEXT column containing JSON.'
    );
    commentedProp(
      'spark.cdm.feature.extractJson.propertyMapping',
      'json_field:target_col',
      'JSON property to target column mapping.'
    );
    commentedProp(
      'spark.cdm.feature.extractJson.exclusive',
      'false',
      'Set to true to process only mapped columns.'
    );
  }

  // ── Filters ───────────────────────────────────────────────────────────────
  section(
    'FILTERS',
    'Partition range and row-level filters. Useful for partial migrations or re-runs.'
  );

  commentedProp(
    'spark.cdm.filter.cassandra.partition.min',
    '-9223372036854775808',
    'Lower bound (inclusive) of token range to migrate. Default: Long.MIN_VALUE.'
  );
  commentedProp(
    'spark.cdm.filter.cassandra.partition.max',
    '9223372036854775807',
    'Upper bound (inclusive) of token range to migrate. Default: Long.MAX_VALUE.'
  );
  commentedProp(
    'spark.cdm.filter.cassandra.whereCondition',
    '',
    "Additional CQL WHERE clause appended to origin SELECT (e.g., status = 'active'). Use ALLOW FILTERING carefully."
  );
  commentedProp(
    'spark.cdm.filter.java.token.percent',
    '100',
    'Percentage (1-100) of tokens per split to migrate. Useful for random sampling/validation.'
  );
  commentedProp(
    'spark.cdm.filter.java.writetime.min',
    '0',
    'Minimum WRITETIME (microseconds since epoch) for rows to migrate.'
  );
  commentedProp(
    'spark.cdm.filter.java.writetime.max',
    '9223372036854775807',
    'Maximum WRITETIME (microseconds since epoch) for rows to migrate.'
  );

  // ── TLS ───────────────────────────────────────────────────────────────────
  section(
    'TLS / SSL (optional)',
    'Uncomment and configure if your clusters require TLS. Not needed when using Astra SCB.'
  );

  commentedProp(
    'spark.cdm.connect.origin.tls.enabled',
    'false',
    'Set to true to enable TLS for origin.'
  );
  commentedProp(
    'spark.cdm.connect.origin.tls.trustStore.path',
    '',
    'Path to Java truststore file.'
  );
  commentedProp('spark.cdm.connect.origin.tls.trustStore.password', '', 'Truststore password.');
  commentedProp(
    'spark.cdm.connect.origin.tls.trustStore.type',
    'JKS',
    'Truststore type (JKS or PKCS12).'
  );
  commentedProp('spark.cdm.connect.origin.tls.keyStore.path', '', 'Path to Java keystore file.');
  commentedProp('spark.cdm.connect.origin.tls.keyStore.password', '', 'Keystore password.');
  commentedProp(
    'spark.cdm.connect.origin.tls.enabledAlgorithms',
    'TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA',
    'Enabled TLS cipher algorithms.'
  );
  lines.push('');
  commentedProp(
    'spark.cdm.connect.target.tls.enabled',
    'false',
    'Set to true to enable TLS for target.'
  );
  commentedProp(
    'spark.cdm.connect.target.tls.trustStore.path',
    '',
    'Path to Java truststore file.'
  );
  commentedProp('spark.cdm.connect.target.tls.trustStore.password', '', 'Truststore password.');
  commentedProp('spark.cdm.connect.target.tls.trustStore.type', 'JKS', 'Truststore type.');
  commentedProp('spark.cdm.connect.target.tls.keyStore.path', '', 'Path to Java keystore file.');
  commentedProp('spark.cdm.connect.target.tls.keyStore.password', '', 'Keystore password.');
  commentedProp(
    'spark.cdm.connect.target.tls.enabledAlgorithms',
    'TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA',
    'Enabled TLS cipher algorithms.'
  );

  lines.push('');
  lines.push('# End of generated cdm.properties');

  return lines.join('\n');
}
