/*
 Copyright DataStax, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

import { describe, it, expect } from 'vitest';
import { generateProperties } from '../utils/generateProperties.js';

// Minimal valid form state
const baseState = () => ({
  originConnectionType: 'host',
  originHost: 'origin-host',
  originPort: 9042,
  originUsername: 'cassandra',
  originPassword: 'cassandra',
  originScb: '',
  originScbMethod: 'provide',
  originAstraDatabaseId: '',
  originScbType: 'default',
  originScbRegion: '',
  originScbCustomDomain: '',

  targetConnectionType: 'host',
  targetHost: 'target-host',
  targetPort: 9042,
  targetUsername: 'cassandra',
  targetPassword: 'cassandra',
  targetScb: '',
  targetScbMethod: 'provide',
  targetAstraDatabaseId: '',
  targetScbType: 'default',
  targetScbRegion: '',
  targetScbCustomDomain: '',

  originSchema: null,
  targetSchema: null,
  originCql: '',
  targetCql: '',

  rowCount: null,
  tableSizeGB: null,
  dataTypes: [],

  explodeMapEnabled: false,
  explodeMapOriginColumn: '',
  explodeMapTargetKeyColumn: '',
  explodeMapTargetValueColumn: '',

  constantColumnsEnabled: false,
  constantColumnsNames: '',
  constantColumnsTypes: '',
  constantColumnsValues: '',

  extractJsonEnabled: false,
  extractJsonOriginColumn: '',
  extractJsonPropertyMapping: '',
  extractJsonExclusive: false,

  autocorrectMissing: false,
  autocorrectMismatch: false,

  trackRun: false,
  trackRunAutoRerun: false,
});

describe('generateProperties', () => {
  // ── Output structure ──────────────────────────────────────────────────────
  it('returns a non-empty string', () => {
    const output = generateProperties(baseState());
    expect(typeof output).toBe('string');
    expect(output.length).toBeGreaterThan(0);
  });

  it('includes header comment', () => {
    const output = generateProperties(baseState());
    expect(output).toContain('# Generated by CDM Config Builder');
  });

  it('includes section headers', () => {
    const output = generateProperties(baseState());
    expect(output).toContain('ORIGIN CONNECTION');
    expect(output).toContain('TARGET CONNECTION');
    expect(output).toContain('SCHEMA');
    expect(output).toContain('PERFORMANCE');
  });

  // ── Host / Port connection ────────────────────────────────────────────────
  it('emits host and port for host connection type', () => {
    const output = generateProperties(baseState());
    expect(output).toContain('spark.cdm.connect.origin.host');
    expect(output).toContain('origin-host');
    expect(output).toContain('spark.cdm.connect.origin.port');
    expect(output).toContain('spark.cdm.connect.target.host');
    expect(output).toContain('target-host');
  });

  it('emits cassandra username/password for host connection', () => {
    const output = generateProperties(baseState());
    expect(output).toMatch(/spark\.cdm\.connect\.origin\.username\s+cassandra/);
    expect(output).toMatch(/spark\.cdm\.connect\.origin\.password\s+cassandra/);
  });

  it('does not emit scb property for host connection', () => {
    const output = generateProperties(baseState());
    expect(output).not.toContain('spark.cdm.connect.origin.scb');
  });

  // ── Astra DB: Provide SCB ─────────────────────────────────────────────────
  it('emits scb path for Astra DB + provide SCB', () => {
    const state = {
      ...baseState(),
      originConnectionType: 'scb',
      originScbMethod: 'provide',
      originScb: 'file:///path/to/bundle.zip',
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.connect.origin.scb');
    expect(output).toContain('file:///path/to/bundle.zip');
  });

  it('emits token as username for Astra DB connection', () => {
    const state = { ...baseState(), originConnectionType: 'scb', originScbMethod: 'provide' };
    const output = generateProperties(state);
    expect(output).toMatch(/spark\.cdm\.connect\.origin\.username\s+token/);
  });

  it('emits AstraCS token as password for Astra DB connection', () => {
    const state = {
      ...baseState(),
      originConnectionType: 'scb',
      originScbMethod: 'provide',
      originPassword: 'AstraCS:abc123',
    };
    const output = generateProperties(state);
    expect(output).toContain('AstraCS:abc123');
  });

  it('does not emit host/port for Astra DB connection', () => {
    const state = { ...baseState(), originConnectionType: 'scb', originScbMethod: 'provide' };
    const output = generateProperties(state);
    expect(output).not.toContain('spark.cdm.connect.origin.host');
    expect(output).not.toContain('spark.cdm.connect.origin.port');
  });

  // ── Astra DB: Auto-download SCB (default type) ────────────────────────────
  it('emits astra.database.id for auto-download SCB', () => {
    const state = {
      ...baseState(),
      originConnectionType: 'scb',
      originScbMethod: 'auto',
      originAstraDatabaseId: '550e8400-e29b-41d4-a716-446655440000',
      originScbType: 'default',
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.connect.origin.astra.database.id');
    expect(output).toContain('550e8400-e29b-41d4-a716-446655440000');
    expect(output).toContain('spark.cdm.connect.origin.astra.scb.type');
    expect(output).toContain('default');
  });

  it('does not emit scb.region or scb.custom.domain for default SCB type', () => {
    const state = {
      ...baseState(),
      originConnectionType: 'scb',
      originScbMethod: 'auto',
      originAstraDatabaseId: '550e8400-e29b-41d4-a716-446655440000',
      originScbType: 'default',
    };
    const output = generateProperties(state);
    expect(output).not.toContain('spark.cdm.connect.origin.astra.scb.region');
    expect(output).not.toContain('spark.cdm.connect.origin.astra.scb.custom.domain');
  });

  // ── Astra DB: Auto-download SCB (custom type) ─────────────────────────────
  it('emits scb.region and scb.custom.domain for custom SCB type', () => {
    const state = {
      ...baseState(),
      originConnectionType: 'scb',
      originScbMethod: 'auto',
      originAstraDatabaseId: '550e8400-e29b-41d4-a716-446655440000',
      originScbType: 'custom',
      originScbRegion: 'us-east-1',
      originScbCustomDomain: 'my-domain.example.com',
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.connect.origin.astra.scb.region');
    expect(output).toContain('us-east-1');
    expect(output).toContain('spark.cdm.connect.origin.astra.scb.custom.domain');
    expect(output).toContain('my-domain.example.com');
  });

  // ── Target Astra DB ───────────────────────────────────────────────────────
  it('handles target Astra DB auto-download with custom SCB', () => {
    const state = {
      ...baseState(),
      targetConnectionType: 'scb',
      targetScbMethod: 'auto',
      targetAstraDatabaseId: 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
      targetScbType: 'custom',
      targetScbRegion: 'eu-west-1',
      targetScbCustomDomain: 'target-domain.example.com',
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.connect.target.astra.database.id');
    expect(output).toContain('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee');
    expect(output).toContain('spark.cdm.connect.target.astra.scb.region');
    expect(output).toContain('eu-west-1');
    expect(output).toContain('spark.cdm.connect.target.astra.scb.custom.domain');
    expect(output).toContain('target-domain.example.com');
  });

  // ── Schema section ────────────────────────────────────────────────────────
  it('emits origin keyspaceTable from parsed schema', () => {
    const state = {
      ...baseState(),
      originSchema: { keyspaceTable: 'myks.mytable' },
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.schema.origin.keyspaceTable');
    expect(output).toContain('myks.mytable');
  });

  it('emits target keyspaceTable when different from origin', () => {
    const state = {
      ...baseState(),
      originSchema: { keyspaceTable: 'ks.origin_tbl' },
      targetSchema: { keyspaceTable: 'ks.target_tbl' },
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.schema.target.keyspaceTable');
    expect(output).toContain('ks.target_tbl');
  });

  it('comments out target keyspaceTable when same as origin', () => {
    const state = {
      ...baseState(),
      originSchema: { keyspaceTable: 'ks.tbl' },
      targetSchema: { keyspaceTable: 'ks.tbl' },
    };
    const output = generateProperties(state);
    // Should be commented out
    expect(output).toMatch(/#spark\.cdm\.schema\.target\.keyspaceTable/);
  });

  // ── Autocorrect ───────────────────────────────────────────────────────────
  it('emits autocorrect.missing=false by default', () => {
    const output = generateProperties(baseState());
    expect(output).toMatch(/spark\.cdm\.autocorrect\.missing\s+false/);
  });

  it('emits autocorrect.missing=true when enabled', () => {
    const state = { ...baseState(), autocorrectMissing: true };
    const output = generateProperties(state);
    expect(output).toMatch(/spark\.cdm\.autocorrect\.missing\s+true/);
  });

  it('emits autocorrect.mismatch=true when enabled', () => {
    const state = { ...baseState(), autocorrectMismatch: true };
    const output = generateProperties(state);
    expect(output).toMatch(/spark\.cdm\.autocorrect\.mismatch\s+true/);
  });

  // ── TrackRun ──────────────────────────────────────────────────────────────
  it('emits trackRun=false by default', () => {
    const output = generateProperties(baseState());
    expect(output).toMatch(/spark\.cdm\.trackRun\s+false/);
  });

  it('emits trackRun=true and autoRerun when enabled', () => {
    const state = { ...baseState(), trackRun: true, trackRunAutoRerun: true };
    const output = generateProperties(state);
    expect(output).toMatch(/spark\.cdm\.trackRun\s+true/);
    expect(output).toMatch(/spark\.cdm\.trackRun\.autoRerun\s+true/);
  });

  // ── Advanced features: ExplodeMap ─────────────────────────────────────────
  it('emits explodeMap properties when enabled', () => {
    const state = {
      ...baseState(),
      explodeMapEnabled: true,
      explodeMapOriginColumn: 'my_map',
      explodeMapTargetKeyColumn: 'map_key',
      explodeMapTargetValueColumn: 'map_value',
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.feature.explodeMap.origin.name');
    expect(output).toContain('my_map');
    expect(output).toContain('spark.cdm.feature.explodeMap.target.name.key');
    expect(output).toContain('map_key');
    expect(output).toContain('spark.cdm.feature.explodeMap.target.name.value');
    expect(output).toContain('map_value');
  });

  it('comments out explodeMap when disabled', () => {
    const output = generateProperties(baseState());
    expect(output).toMatch(/#spark\.cdm\.feature\.explodeMap\.origin\.name/);
  });

  // ── Advanced features: ConstantColumns ───────────────────────────────────
  it('emits constantColumns properties when enabled', () => {
    const state = {
      ...baseState(),
      constantColumnsEnabled: true,
      constantColumnsNames: 'col1,col2',
      constantColumnsTypes: 'text,int',
      constantColumnsValues: "'val1',42",
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.feature.constantColumns.names');
    expect(output).toContain('col1,col2');
    expect(output).toContain('spark.cdm.feature.constantColumns.types');
    expect(output).toContain('spark.cdm.feature.constantColumns.values');
  });

  // ── Advanced features: ExtractJson ───────────────────────────────────────
  it('emits extractJson properties when enabled', () => {
    const state = {
      ...baseState(),
      extractJsonEnabled: true,
      extractJsonOriginColumn: 'json_col',
      extractJsonPropertyMapping: 'field:target_col',
      extractJsonExclusive: true,
    };
    const output = generateProperties(state);
    expect(output).toContain('spark.cdm.feature.extractJson.originColumn');
    expect(output).toContain('json_col');
    expect(output).toContain('spark.cdm.feature.extractJson.propertyMapping');
    expect(output).toContain('field:target_col');
    expect(output).toMatch(/spark\.cdm\.feature\.extractJson\.exclusive\s+true/);
  });

  // ── TLS section ───────────────────────────────────────────────────────────
  it('includes TLS section (commented out)', () => {
    const output = generateProperties(baseState());
    expect(output).toContain('TLS');
    expect(output).toMatch(/#spark\.cdm\.connect\.origin\.tls\.enabled/);
    expect(output).toMatch(/#spark\.cdm\.connect\.target\.tls\.enabled/);
  });

  // ── Filters section ───────────────────────────────────────────────────────
  it('includes filters section (commented out)', () => {
    const output = generateProperties(baseState());
    expect(output).toMatch(/#spark\.cdm\.filter\.cassandra\.partition\.min/);
    expect(output).toMatch(/#spark\.cdm\.filter\.cassandra\.partition\.max/);
  });

  // ── End marker ────────────────────────────────────────────────────────────
  it('ends with end-of-file comment', () => {
    const output = generateProperties(baseState());
    expect(output).toContain('# End of generated cdm.properties');
  });
});
