name: Build and test jar with integration tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  CDM-Integration-Test:
    strategy:
      matrix:
        jdk: [ 8 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - name: Test SIT with cdm
        working-directory: SIT
        run: |
          echo "Testing SIT with cdm"
          make -f Makefile
