name: Build and test jar with integration tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  CDM-Integration-Test:
    concurrency:
      group: ${{ github.ref }}-${{ github.job }}-${{ matrix.jdk }}-${{ matrix.os }}
      cancel-in-progress: true
    strategy:
      matrix:
        jdk: [ 8 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven
      - name: Test SIT with cdm
        working-directory: SIT
        run: |
          echo "Testing SIT with cdm"
          make -f Makefile
