# GitHub Action CI
# Snyk clean-up when PR is merged/closed

on:
  pull_request:
    types:
      - closed
    branches:    
      - main
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  #group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job || github.run_id }}
  cancel-in-progress: true

